apiVersion: batch/v1
kind: Job
metadata:
  name: testing-job
  labels:
    app: testing-job
spec:
  template:
    metadata:
      name: testing-job
      labels:
        app: testing-job
    spec:
      containers:
      - name: testing-job
        image: python:3.7.6-alpine3.10
        command: ['sh', '-c', 'sleep 15']
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst