apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-4
  labels:
    app: test-job-4
spec:
  template:
    metadata:
      name: test-job-4
      labels:
        app: test-job-4
    spec:
      containers:
      - name: test-job-4
        image: python:3.7.6-alpine3.10
        command: ['sh', '-c', 'sleep 15']
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst