apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpatest
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hpatest
  targetCPUUtilizationPercentage: 70
